services:
  - type: web
    name: grably
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y python3-pip
      pip install yt-dlp
      npm install
    startCommand: node server.js
